---
- name: yum-plugin-fastestmirror installed
  yum:
    name: yum-plugin-fastestmirror
    state: present

- name: ELREPO GPG key imported
  rpm_key:
    key: http://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present

- name: ELREPO package installed (CentOS 6 ver)
  yum:
    name: http://www.elrepo.org/elrepo-release-6-8.el6.elrepo.noarch.rpm
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "6"

- name: ELREPO package installed (CentOS 7 ver)
  yum:
    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
...
